package manager changes

diff --git a/pkg/pkg b/pkg/pkg
--- a/pkg/pkg
+++ b/pkg/pkg
@@ -52,49 +52,72 @@ installed() {
 
 install() {
   echo "checking mirror..."
-  if ! exists "$1"; then
-    echo "$1 does not exist"
+  for PKG in $@; do
+    if ! exists "$PKG"; then
+    echo "$PKG does not exist"
     exit 1
-  fi
+    fi
 
-  if ! installed $1; then
+    if ! installed "$PKG"; then
     exit 1
-  fi
+    fi
 
-  read -p "Are you sure you want to install $1? [Y/n]: " ANSWER
-  case $ANSWER in
-  "Y") ;;
+    read -p "Are you sure you want to install $PKG? [Y/n]: " ANSWER
+    case $ANSWER in
+    "Y") ;;
 
-  *)
-    echo "installation of $1 aborted"
+    *)
+    echo "installation of $PKG aborted"
     exit 1
     ;;
-  esac
-  echo "Installing $1" 1>&2
-  echo "installing from $URL/sources/$1.php" 1>&2
-  curl "$URL/sources/$1.php" 2>/dev/null | sed "s/<br>//g" >>"$DIR/../words/$1.txt"
-  echo "$1" >>"$DIR/pkg.lock"
+    esac
+    echo "Installing $PKG" 1>&2
+    echo "installing from $URL/sources/$PKG.php" 1>&2
+    curl "$URL/sources/$PKG.php" 2>/dev/null | sed "s/<br>//g" >>"$DIR/../words/$1.txt"
+    echo "$PKG" >>"$DIR/pkg.lock"
+  done
 }
 
 remove() {
-  if ! exists "$1"; then
-    echo "$1 does not exist"
+  for PKG in $@; do
+    if ! exists "$PKG"; then
+    echo "$PKG does not exist"
     exit 1
-  fi
-  read -p "Are you sure you want to uninstall $1? [Y/n]: " ANSWER
-  case $ANSWER in
-  "Y") ;;
-  *)
-    echo "removal of $1 aborted"
+    fi
+    read -p "Are you sure you want to uninstall $PKG? [Y/n]: " ANSWER
+    case $ANSWER in
+    "Y") ;;
+    *)
+    echo "removal of $PKG aborted"
     exit 1
-  ;;
-  esac
-  rm -rf "$DIR/../words/$1.txt"
-  grep -v "$1" "$DIR/pkg.lock" >>"$DIR/pkg.lock.tmp"
-  mv "$DIR/pkg.lock.tmp" "$DIR/pkg.lock"
+    ;;
+    esac
+    rm -rf "$DIR/../words/$PKG.txt"
+    grep -v "$PKG" "$DIR/pkg.lock" >>"$DIR/pkg.lock.tmp"
+    mv "$DIR/pkg.lock.tmp" "$DIR/pkg.lock"
+  done
 }
 
 CMD=$1
 shift
-# shellcheck disable=SC2068
-$CMD $@
+case "$CMD" in
+    "install")
+        install $@
+    ;;
+    "remove")
+        remove $@
+    ;;
+    "search")
+        search $@
+    ;;
+    "list")
+        list $@
+    ;;
+    "-h")
+        less $DIR/README.md
+    ;;
+    *)
+        echo "Undefined command $CMD." 1>&2
+        exit 127
+    ;;
+esac
