upgrade functionality on pkg

diff --git a/pkg/pkg b/pkg/pkg
--- a/pkg/pkg
+++ b/pkg/pkg
@@ -30,10 +30,8 @@ list() {
 }
 
 exists() {
-  echo "checking verbs" 1>&2
   curl https://ola11-sources.herokuapp.com/verb.php 2>/dev/null | grep "sources/$1.php" >/dev/null
   if [ $? -ne 0 ]; then
-    echo "checking nouns" 1>&2
     curl https://ola11-sources.herokuapp.com/noun.php 2>/dev/null | grep "sources/$1.php" >/dev/null
     [ $? -eq 0 ] && return 0
     return 1
@@ -44,14 +42,18 @@ exists() {
 installed() {
   [ -f "$DIR/pkg.lock" ] && grep "$1" $DIR/pkg.lock >/dev/null
   if [ $? -eq 0 ]; then
-    echo "package $1 already installed"
+    echo "package $1 already installed" 1>&2
     return 1
   fi
   return 0
 }
 
 install() {
-  echo "checking mirror..."
+  echo "checking mirror..." 1>&2
+  FLAG=$1
+  if [ $FLAG == "--no-flag" ]; then
+      shift
+  fi
   for PKG in $@; do
     if ! exists "$PKG"; then
     echo "$PKG does not exist"
@@ -62,15 +64,17 @@ install() {
     exit 1
     fi
 
-    read -p "Are you sure you want to install $PKG? [Y/n]: " ANSWER
-    case $ANSWER in
-    "Y") ;;
+    if [ $FLAG != "--no-flag" ]; then
+        read -p "Are you sure you want to install $PKG? [Y/n]: " ANSWER
+        case $ANSWER in
+        "Y") ;;
 
-    *)
-    echo "installation of $PKG aborted"
-    exit 1
-    ;;
-    esac
+        *)
+        echo "installation of $PKG aborted" 1>&2
+        exit 1
+        ;;
+        esac
+    fi
     echo "Installing $PKG" 1>&2
     echo "installing from $URL/sources/$PKG.php" 1>&2
     curl "$URL/sources/$PKG.php" 2>/dev/null | sed "s/<br>//g" >> "$DIR/../words/$PKG.txt"
@@ -79,23 +83,39 @@ install() {
 }
 
 remove() {
+  FLAG=$1
+  if [ $FLAG == "--no-flag" ]; then
+      shift
+  fi
   for PKG in $@; do
-    if ! exists "$PKG"; then
-    echo "$PKG does not exist"
+    if ! grep "$PKG" $DIR/pkg.lock > /dev/null ; then
+    echo "$PKG does not exist" 1>&2
     exit 1
     fi
-    read -p "Are you sure you want to uninstall $PKG? [Y/n]: " ANSWER
-    case $ANSWER in
-    "Y") ;;
-    *)
-    echo "removal of $PKG aborted"
-    exit 1
-    ;;
-    esac
+    if [ $FLAG != "--no-flag" ]; then
+        read -p "Are you sure you want to uninstall $PKG? [Y/n]: " ANSWER
+        case $ANSWER in
+        "Y") ;;
+        *)
+        echo "removal of $PKG aborted" 1>&2
+        exit 1
+        ;;
+        esac
+    fi
     rm -rf "$DIR/../words/$PKG.txt"
     grep -v "$PKG" "$DIR/pkg.lock" >>"$DIR/pkg.lock.tmp"
     mv "$DIR/pkg.lock.tmp" "$DIR/pkg.lock"
   done
+}
+
+upgrade() {
+    PACKAGES=$(list)
+    for P in $PACKAGES; do
+        echo "Updating $P" 1>&2
+        remove --no-flag $P
+        install --no-flag $P
+        echo "" 1>&2
+    done
 }
 
 CMD=$1
@@ -112,6 +132,9 @@ case "$CMD" in
     ;;
     "list")
         list $@
+    ;;
+    "upgrade")
+         upgrade $@
     ;;
     "-h")
         less $DIR/README.md
